name: Feature Request
description: Request and enhancement or a change to the way Custom Element Plugin CEP works.
title: "[Feature]: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this feature request. Any submissions to the LSP repository should have a issue. Any submissions that require breaking changes must have an issue and a discussion.

- type: textarea
  id: info
  attributes:
    label: Feature Request Info
    description: Tell us about your feature request.
    placeholder: Tell us about your feature request.
  validations:
    required: true

- type: textarea
  id: benefit
  attributes:
    label: What benefit would this feature bring?
    description: Explain the benefit of adding this feature.
    placeholder: Tell us about your feature request.
  validations:
    required: true

- type: textarea
  id: requirement
  attributes:
    label: Why does enhancement require a change to the core repository?
    description: Have you seen there is a plugin API? (Not until FUI-1331) Please explain why this change is best suited to the code of this repository. This could be changes to the core code, or other plugins maintained in this repository such as the MS FAST plugin.
    placeholder: Why shouldn't this be created via the plugin API?
  validations:
    required: true


- type: textarea
  id: other-info
  attributes:
    label: Any of info
    description: If you have any other relevant info then please write it in this box. This could include any progress you've made with implementing the enhancement yourself.
    placeholder: If you have any other relevant info then please write it in this box.
  validations:
    required: false

- type: checkboxes
  id: terms
  attributes:
    label: Submission Guidelines
    description: By submitting this issue, you agree to follow our [Contributing Guidlines](https://github.com/genesiscommunitysuccess/custom-elements-lsp/blob/master/CONTRIBUTING.md) and have checked that this issue has not already been raised [on the issue tracker](https://github.com/genesiscommunitysuccess/custom-elements-lsp/issues).
    options:
      - label: I agree to the guidelines stated.
        required: true
