name: CI

on:
  push:
    branches: [ master, prerelease ]

jobs:
  Publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_USER_TOKEN}}

      - name: Configure Node 18
        uses: actions/setup-node@v3

      - name: Bootstrap
        run: npm run bootstrap:ci

        # Fails the build if the working tree is dirty
        # which happens when you don't update the API docs in line
        # with the tsdoc comments
      - name: Check working tree
        run: test -z "$(git status --porcelain)"

      - name: Lint
        run: npm run lint:eslint:all

      - name: Unit Test
        run: npm run test:unit

      - name: "NPM Identity"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - name: Release
        env:
          GH_TOKEN: ${{secrets.GH_USER_TOKEN}}
        run: npm run release
